"""create notes table

Revision ID: 669c4e7f2605
Revises: 
Create Date: 2026-09-26 23:30:29.226659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669c4e7f2605'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notes')
    # ### end Alembic commands ###
